/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('./src/components/ui/InputText.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Stock: typeof import('./src/components/Stock.vue')['default']
    StockChart: typeof import('./src/components/StockChart.vue')['default']
    Stocks: typeof import('./src/components/Stocks.vue')['default']
    TextField: typeof import('./src/components/ui/InputText.vue')['default']
  }
}
