/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    TextField: typeof import('./src/components/ui/TextField.vue')['default']
  }
}
